Part 1 : Male and Female analysis

In [236]:
# Loading usefull librairies
import pandas as pd

import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

import plotly.graph_objects as go
import plotly.offline as pyo
import plotly.io as pio

# Display all columns in the .head()
pd.options.display.max_columns = 1000

In [237]:
# Loading the dataset
dataset = pd.read_csv('src/Speed_Dating_Data.csv',encoding='ISO-8859-1')

In [238]:
# Visualize the 5 first roww of the dataset
dataset.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [239]:
# Checking the shape
dataset.shape

(8378, 195)

SCALING WAVE TO 10 PTS FOR ALL THE DATASET

In [240]:
# Listing the wave were 100 pts has been evaluated
list_waves = [1,2,3,4,5,10,11,12,13,14,15,16,17,18,19,20,21]

In [132]:
# Getting the list of columns names
dataset.columns.to_list()

['iid',
 'id',
 'gender',
 'idg',
 'condtn',
 'wave',
 'round',
 'position',
 'positin1',
 'order',
 'partner',
 'pid',
 'match',
 'int_corr',
 'samerace',
 'age_o',
 'race_o',
 'pf_o_att',
 'pf_o_sin',
 'pf_o_int',
 'pf_o_fun',
 'pf_o_amb',
 'pf_o_sha',
 'dec_o',
 'attr_o',
 'sinc_o',
 'intel_o',
 'fun_o',
 'amb_o',
 'shar_o',
 'like_o',
 'prob_o',
 'met_o',
 'age',
 'field',
 'field_cd',
 'undergra',
 'mn_sat',
 'tuition',
 'race',
 'imprace',
 'imprelig',
 'from',
 'zipcode',
 'income',
 'goal',
 'date',
 'go_out',
 'career',
 'career_c',
 'sports',
 'tvsports',
 'exercise',
 'dining',
 'museums',
 'art',
 'hiking',
 'gaming',
 'clubbing',
 'reading',
 'tv',
 'theater',
 'movies',
 'concerts',
 'music',
 'shopping',
 'yoga',
 'exphappy',
 'expnum',
 'attr1_1',
 'sinc1_1',
 'intel1_1',
 'fun1_1',
 'amb1_1',
 'shar1_1',
 'attr4_1',
 'sinc4_1',
 'intel4_1',
 'fun4_1',
 'amb4_1',
 'shar4_1',
 'attr2_1',
 'sinc2_1',
 'intel2_1',
 'fun2_1',
 'amb2_1',
 'shar2_1',
 'attr3_1',
 'sinc3_1',
 'fun3_1',
 'intel3_1',
 'amb3_1',
 'attr5_1',
 'sinc5_1',
 'intel5_1',
 'fun5_1',
 'amb5_1',
 'dec',
 'attr',
 'sinc',
 'intel',
 'fun',
 'amb',
 'shar',
 'like',
 'prob',
 'met',
 'match_es',
 'attr1_s',
 'sinc1_s',
 'intel1_s',
 'fun1_s',
 'amb1_s',
 'shar1_s',
 'attr3_s',
 'sinc3_s',
 'intel3_s',
 'fun3_s',
 'amb3_s',
 'satis_2',
 'length',
 'numdat_2',
 'attr7_2',
 'sinc7_2',
 'intel7_2',
 'fun7_2',
 'amb7_2',
 'shar7_2',
 'attr1_2',
 'sinc1_2',
 'intel1_2',
 'fun1_2',
 'amb1_2',
 'shar1_2',
 'attr4_2',
 'sinc4_2',
 'intel4_2',
 'fun4_2',
 'amb4_2',
 'shar4_2',
 'attr2_2',
 'sinc2_2',
 'intel2_2',
 'fun2_2',
 'amb2_2',
 'shar2_2',
 'attr3_2',
 'sinc3_2',
 'intel3_2',
 'fun3_2',
 'amb3_2',
 'attr5_2',
 'sinc5_2',
 'intel5_2',
 'fun5_2',
 'amb5_2',
 'you_call',
 'them_cal',
 'date_3',
 'numdat_3',
 'num_in_3',
 'attr1_3',
 'sinc1_3',
 'intel1_3',
 'fun1_3',
 'amb1_3',
 'shar1_3',
 'attr7_3',
 'sinc7_3',
 'intel7_3',
 'fun7_3',
 'amb7_3',
 'shar7_3',
 'attr4_3',
 'sinc4_3',
 'intel4_3',
 'fun4_3',
 'amb4_3',
 'shar4_3',
 'attr2_3',
 'sinc2_3',
 'intel2_3',
 'fun2_3',
 'amb2_3',
 'shar2_3',
 'attr3_3',
 'sinc3_3',
 'intel3_3',
 'fun3_3',
 'amb3_3',
 'attr5_3',
 'sinc5_3',
 'intel5_3',
 'fun5_3',
 'amb5_3']

In [241]:
# List of feature to change into 10 pts instead of 100pts in waves from list_waves
list_waves_100 = [
            'attr1_1',
            'sinc1_1',
            'intel1_1',
            'fun1_1',
            'amb1_1',
            'shar1_1',

            'attr4_1',
            'sinc4_1',
            'intel4_1',
            'fun4_1',
            'amb4_1',
            'shar4_1',

            'attr2_1',
            'sinc2_1',
            'intel2_1',
            'fun2_1',
            'amb2_1',
            'shar2_1',

            'attr1_2',
            'sinc1_2',
            'intel1_2',
            'fun1_2',
            'amb1_2',
            'shar1_2']

In [242]:
# List of features to change into 10 pts were 100 pts has been attribute in the full dataset

list_full = ['attr7_2',
            'sinc7_2',
            'intel7_2',
            'fun7_2',
            'amb7_2',
            'shar7_2',

            'attr4_2',
            'sinc4_2',
            'intel4_2',
            'fun4_2',
            'amb4_2',
            'shar4_2',

            'attr2_2',
            'sinc2_2',
            'intel2_2',
            'fun2_2',
            'amb2_2',
            'shar2_2',

            'attr1_3',
            'sinc1_3',
            'intel1_3',
            'fun1_3',
            'amb1_3',
            'shar1_3',

            'attr7_3',
            'sinc7_3',
            'intel7_3',
            'fun7_3',
            'amb7_3',
            'shar7_3']

In [243]:
# Modifing value into 10 pts instead of 100 pts for only the list_waves row
dataset.loc[list_waves, list_waves_100] = (dataset.loc[list_waves, list_waves_100]) /10

In [248]:
dataset.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,Female,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.440,16.670,13.890,22.220,11.110,16.670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,1.5,2.0,2.0,1.5,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,Female,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,1.5,2.0,2.0,1.5,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,3.5,2.0,1.5,2.0,0.5,0.5,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.944,1.667,1.389,2.222,1.111,1.667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,1.5,2.0,2.0,1.5,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,Female,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,1.5,2.0,2.0,1.5,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,3.5,2.0,1.5,2.0,0.5,0.5,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.944,1.667,1.389,2.222,1.111,1.667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,1.5,2.0,2.0,1.5,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,Female,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,1.5,2.0,2.0,1.5,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,3.5,2.0,1.5,2.0,0.5,0.5,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.944,1.667,1.389,2.222,1.111,1.667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,1.5,2.0,2.0,1.5,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,Female,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,1.5,2.0,2.0,1.5,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,3.5,2.0,1.5,2.0,0.5,0.5,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.944,1.667,1.389,2.222,1.111,1.667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,1.5,2.0,2.0,1.5,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [245]:
# Modifing value to get the rate under 10 pts instead of 100

dataset.loc[:, list_full] = (dataset.loc[:, list_full]) /10

REMPLACEMENT DES NUMERO PAR LE TEXTE ASSOCIE

In [247]:
dataset["gender"] = dataset["gender"].apply(lambda x : "Male" if x==1 else "Female")

REPLACE MISSING VALUES

In [204]:
data.columns.to_list()

['iid',
 'id',
 'gender',
 'idg',
 'condtn',
 'wave',
 'round',
 'position',
 'positin1',
 'order',
 'partner',
 'pid',
 'match',
 'int_corr',
 'samerace',
 'age_o',
 'race_o',
 'pf_o_att',
 'pf_o_sin',
 'pf_o_int',
 'pf_o_fun',
 'pf_o_amb',
 'pf_o_sha',
 'dec_o',
 'attr_o',
 'sinc_o',
 'intel_o',
 'fun_o',
 'amb_o',
 'shar_o',
 'like_o',
 'prob_o',
 'met_o',
 'age',
 'field',
 'field_cd',
 'undergra',
 'mn_sat',
 'tuition',
 'race',
 'imprace',
 'imprelig',
 'from',
 'zipcode',
 'income',
 'goal',
 'date',
 'go_out',
 'career',
 'career_c',
 'sports',
 'tvsports',
 'exercise',
 'dining',
 'museums',
 'art',
 'hiking',
 'gaming',
 'clubbing',
 'reading',
 'tv',
 'theater',
 'movies',
 'concerts',
 'music',
 'shopping',
 'yoga',
 'exphappy',
 'expnum',
 'attr1_1',
 'sinc1_1',
 'intel1_1',
 'fun1_1',
 'amb1_1',
 'shar1_1',
 'attr4_1',
 'sinc4_1',
 'intel4_1',
 'fun4_1',
 'amb4_1',
 'shar4_1',
 'attr2_1',
 'sinc2_1',
 'intel2_1',
 'fun2_1',
 'amb2_1',
 'shar2_1',
 'attr3_1',
 'sinc3_1',
 'fun3_1',
 'intel3_1',
 'amb3_1',
 'attr5_1',
 'sinc5_1',
 'intel5_1',
 'fun5_1',
 'amb5_1',
 'dec',
 'attr',
 'sinc',
 'intel',
 'fun',
 'amb',
 'shar',
 'like',
 'prob',
 'met',
 'match_es',
 'attr1_s',
 'sinc1_s',
 'intel1_s',
 'fun1_s',
 'amb1_s',
 'shar1_s',
 'attr3_s',
 'sinc3_s',
 'intel3_s',
 'fun3_s',
 'amb3_s',
 'satis_2',
 'length',
 'numdat_2',
 'attr7_2',
 'sinc7_2',
 'intel7_2',
 'fun7_2',
 'amb7_2',
 'shar7_2',
 'attr1_2',
 'sinc1_2',
 'intel1_2',
 'fun1_2',
 'amb1_2',
 'shar1_2',
 'attr4_2',
 'sinc4_2',
 'intel4_2',
 'fun4_2',
 'amb4_2',
 'shar4_2',
 'attr2_2',
 'sinc2_2',
 'intel2_2',
 'fun2_2',
 'amb2_2',
 'shar2_2',
 'attr3_2',
 'sinc3_2',
 'intel3_2',
 'fun3_2',
 'amb3_2',
 'attr5_2',
 'sinc5_2',
 'intel5_2',
 'fun5_2',
 'amb5_2',
 'you_call',
 'them_cal',
 'date_3',
 'numdat_3',
 'num_in_3',
 'attr1_3',
 'sinc1_3',
 'intel1_3',
 'fun1_3',
 'amb1_3',
 'shar1_3',
 'attr7_3',
 'sinc7_3',
 'intel7_3',
 'fun7_3',
 'amb7_3',
 'shar7_3',
 'attr4_3',
 'sinc4_3',
 'intel4_3',
 'fun4_3',
 'amb4_3',
 'shar4_3',
 'attr2_3',
 'sinc2_3',
 'intel2_3',
 'fun2_3',
 'amb2_3',
 'shar2_3',
 'attr3_3',
 'sinc3_3',
 'intel3_3',
 'fun3_3',
 'amb3_3',
 'attr5_3',
 'sinc5_3',
 'intel5_3',
 'fun5_3',
 'amb5_3']

In [206]:
usefull_col_na = [
                    'attr1_1',
                    'sinc1_1',
                    'intel1_1',
                    'fun1_1',
                    'amb1_1',
                    'shar1_1',
                    'attr4_1',
                    'sinc4_1',
                    'intel4_1',
                    'fun4_1',
                    'amb4_1',
                    'shar4_1',
                    'attr2_1',
                    'sinc2_1',
                    'intel2_1',
                    'fun2_1',
                    'amb2_1',
                    'shar2_1',
                    'attr3_1',
                    'sinc3_1',
                    'fun3_1',
                    'intel3_1',
                    'amb3_1',
                    'attr5_1',
                    'sinc5_1',
                    'intel5_1',
                    'fun5_1',
                    'amb5_1',
                    'attr1_s',
                    'sinc1_s',
                    'intel1_s',
                    'fun1_s',
                    'amb1_s',
                    'shar1_s',
                    'attr3_s',
                    'sinc3_s',
                    'intel3_s',
                    'fun3_s',
                    'amb3_s',
                    'attr7_2',
                    'sinc7_2',
                    'intel7_2',
                    'fun7_2',
                    'amb7_2',
                    'shar7_2',
                    'attr1_2',
                    'sinc1_2',
                    'intel1_2',
                    'fun1_2',
                    'amb1_2',
                    'shar1_2',
                    'attr4_2',
                    'sinc4_2',
                    'intel4_2',
                    'fun4_2',
                    'amb4_2',
                    'shar4_2',
                    'attr2_2',
                    'sinc2_2',
                    'intel2_2',
                    'fun2_2',
                    'amb2_2',
                    'shar2_2',
                    'attr3_2',
                    'sinc3_2',
                    'intel3_2',
                    'fun3_2',
                    'amb3_2',
                    'attr5_2',
                    'sinc5_2',
                    'intel5_2',
                    'fun5_2',
                    'amb5_2',
                    'attr1_3',
                    'sinc1_3',
                    'intel1_3',
                    'fun1_3',
                    'amb1_3',
                    'shar1_3',
                    'attr7_3',
                    'sinc7_3',
                    'intel7_3',
                    'fun7_3',
                    'amb7_3',
                    'shar7_3',
                    'attr4_3',
                    'sinc4_3',
                    'intel4_3',
                    'fun4_3',
                    'amb4_3',
                    'shar4_3',
                    'attr2_3',
                    'sinc2_3',
                    'intel2_3',
                    'fun2_3',
                    'amb2_3',
                    'shar2_3',
                    'attr3_3',
                    'sinc3_3',
                    'intel3_3',
                    'fun3_3',
                    'amb3_3',
                    'attr5_3',
                    'sinc5_3',
                    'intel5_3',
                    'fun5_3',
                    'amb5_3']

In [249]:
for feature in usefull_col_na:
    mean_feature=data[feature].mean()
    data[feature].fillna(value=mean_feature, inplace=True)

In [250]:
# Groupby idd to get one row for 1 people with minimum of NaN values
df = data.loc[data.isnull().sum(axis=1).groupby(data.iid).idxmin(),:]

In [251]:
df.shape

(551, 195)

In [ ]:
# Creating data with only features needed

In [252]:
col_df = ['iid',
        'id',
        'gender',
        'wave',
        'attr1_1',
        'sinc1_1',
        'intel1_1',
        'fun1_1',
        'amb1_1',
        'shar1_1',
        'attr4_1',
        'sinc4_1',
        'intel4_1',
        'fun4_1',
        'amb4_1',
        'shar4_1',
        'attr2_1',
        'sinc2_1',
        'intel2_1',
        'fun2_1',
        'amb2_1',
        'shar2_1',
        'attr3_1',
        'sinc3_1',
        'fun3_1',
        'intel3_1',
        'amb3_1',
        'attr5_1',
        'sinc5_1',
        'intel5_1',
        'fun5_1',
        'amb5_1',
        'attr1_s',
        'sinc1_s',
        'intel1_s',
        'fun1_s',
        'amb1_s',
        'shar1_s',
        'attr3_s',
        'sinc3_s',
        'intel3_s',
        'fun3_s',
        'amb3_s',
        'attr7_2',
        'sinc7_2',
        'intel7_2',
        'fun7_2',
        'amb7_2',
        'shar7_2',
        'attr1_2',
        'sinc1_2',
        'intel1_2',
        'fun1_2',
        'amb1_2',
        'shar1_2',
        'attr4_2',
        'sinc4_2',
        'intel4_2',
        'fun4_2',
        'amb4_2',
        'shar4_2',
        'attr2_2',
        'sinc2_2',
        'intel2_2',
        'fun2_2',
        'amb2_2',
        'shar2_2',
        'attr3_2',
        'sinc3_2',
        'intel3_2',
        'fun3_2',
        'amb3_2',
        'attr5_2',
        'sinc5_2',
        'intel5_2',
        'fun5_2',
        'amb5_2',
        'attr1_3',
        'sinc1_3',
        'intel1_3',
        'fun1_3',
        'amb1_3',
        'shar1_3',
        'attr7_3',
        'sinc7_3',
        'intel7_3',
        'fun7_3',
        'amb7_3',
        'shar7_3',
        'attr4_3',
        'sinc4_3',
        'intel4_3',
        'fun4_3',
        'amb4_3',
        'shar4_3',
        'attr2_3',
        'sinc2_3',
        'intel2_3',
        'fun2_3',
        'amb2_3',
        'shar2_3',
        'attr3_3',
        'sinc3_3',
        'intel3_3',
        'fun3_3',
        'amb3_3',
        'attr5_3',
        'sinc5_3',
        'intel5_3',
        'fun5_3',
        'amb5_3']

In [253]:
df = pd.DataFrame(data = df, columns = col_df)

In [254]:
df.shape

(551, 111)

SPLITTING DATA INTO FEMALE and MALE

In [255]:
df_m = df.loc[df.gender == 'Male',:]

In [256]:
df_f = df.loc[df.gender == 'Female',:]

CREATING 5 DATASET STEP1

In [217]:
question1 =  ['iid',
            'id',
            'gender',
            'wave',
            
            'attr1_1',
            'sinc1_1',
            'intel1_1',
            'fun1_1',
            'amb1_1',
            'shar1_1',
            
            'attr1_2',
            'sinc1_2',
            'intel1_2',
            'fun1_2',
            'amb1_2',
            'shar1_2',
            
            'attr1_3',
            'sinc1_3',
            'intel1_3',
            'fun1_3',
            'amb1_3',
            'shar1_3']

In [219]:
question2 =['iid',
            'id',
            'gender',
            'wave',
            
            'attr4_1',
            'sinc4_1',
            'intel4_1',
            'fun4_1',
            'amb4_1',
            'shar4_1',
            
            'attr4_2',
            'sinc4_2',
            'intel4_2',
            'fun4_2',
            'amb4_2',
            'shar4_2',
            
            'attr4_3',
            'sinc4_3',
            'intel4_3',
            'fun4_3',
            'amb4_3',
            'shar4_3'
            ]

In [220]:
question3 =['iid',
            'id',
            'gender',
            'wave',
            
            'attr2_1',
            'sinc2_1',
            'intel2_1',
            'fun2_1',
            'amb2_1',
            'shar2_1',
            
            'attr2_2',
            'sinc2_2',
            'intel2_2',
            'fun2_2',
            'amb2_2',
            'shar2_2',

            'attr2_3',
            'sinc2_3',
            'intel2_3',
            'fun2_3',
            'amb2_3',
            'shar2_3'
            ]

In [221]:
question4 = ['iid',
            'id',
            'gender',
            'wave',

            'attr3_1',
            'sinc3_1',
            'intel3_1',
            'fun3_1',
            'amb3_1'

            'attr3_2',
            'sinc3_2',
            'intel3_2',
            'fun3_2',
            'amb3_2',

            'attr3_3',
            'sinc3_3',
            'intel3_3',
            'fun3_3',
            'amb3_3']

In [222]:
question5 = ['iid',
            'id',
            'gender',
            'wave',

            'attr5_1',
            'sinc5_1',
            'intel5_1',
            'fun5_1',
            'amb5_1',

            'attr5_2',
            'sinc5_2',
            'intel5_2',
            'fun5_2',
            'amb5_2',
            
            'attr5_3',
            'sinc5_3',
            'intel5_3',
            'fun5_3',
            'amb5_3']

In [223]:
attribute_rating= ['iid',
                    'id',
                    'gender',
                    'wave',

                    'attr7_2',
                    'sinc7_2',
                    'intel7_2',
                    'fun7_2',
                    'amb7_2',
                    'shar7_2',

                    'attr7_3',
                    'sinc7_3',
                    'intel7_3',
                    'fun7_3',
                    'amb7_3',
                    'shar7_3']

CREATING 5 DATASETS STEP 2

In [257]:
df_1_f = pd.DataFrame(df_f, columns = question1)

In [258]:
df_1_m = pd.DataFrame(df_m, columns = question1)

In [259]:
df_2_f = pd.DataFrame(df_f, columns = question2)

In [260]:
df_2_m = pd.DataFrame(df_m, columns = question2)

In [261]:
df_3_f = pd.DataFrame(df_f, columns = question3)

In [262]:
df_3_m = pd.DataFrame(df_m, columns = question3)

In [263]:
df_4_f = pd.DataFrame(df_f, columns = question4)

In [264]:
df_4_m = pd.DataFrame(df_m, columns = question4)

In [265]:
df_5_f = pd.DataFrame(df_f, columns = question5)

In [266]:
df_5_m = pd.DataFrame(df_m, columns = question5)

 ## ANALYSIS

## BEFORE DATE

What you look for in the opposite sex ?

Female - What looking for in the opposite sex

In [159]:
df_1_f = []
for item in columns_1:
    mean = data_f[item].mean()
    mean_list_f_1.append(mean)

In [160]:
dic_f_1 = {'attr1_s': [mean_list_f_1[0]], 
        'sinc1_s': [mean_list_f_1[1]],
        'intel1_s': [mean_list_f_1[2]],
        'fun1_s': [mean_list_f_1[3]],
        'amb1_s': [mean_list_f_1[4]],
        'shar1_s': [mean_list_f_1[5]],
}

In [161]:
df_f_1 = pd.DataFrame(data = dic_f_1)

In [162]:
df_f_1

     attr1_s    sinc1_s  intel1_s     fun1_s     amb1_s    shar1_s
0  17.752714  18.172045  20.77026  17.198736  12.785019  12.681045

In [163]:
categories = ['Attractive', 'Sincere', 'Intelligent', 'Fun', 'Ambitious', 'Share Interests']
categories = [*categories, categories[0]]

mean_attribute = mean_list_f_1
mean_attribute = [*mean_attribute, mean_attribute[0]]



fig = go.Figure(
    data=[
        go.Scatterpolar(r=mean_attribute, theta=categories, fill='toself', name='mean_attribute'),

    ],
    layout=go.Layout(
        title=go.layout.Title(text='Female - What looking for in the opposite sex'),
        polar={'radialaxis': {'visible': True}},
        showlegend=True
    )
)

pyo.plot(fig);

Male - What looking for in the opposite sex

In [164]:
mean_list_m_1 = []
for item in columns_1:
    mean = data_m[item].mean()
    mean_list_m_1.append(mean)

dic_m_1 = {'attr1_s': [mean_list_m_1[0]], 
        'sinc1_s': [mean_list_m_1[1]],
        'intel1_s': [mean_list_m_1[2]],
        'fun1_s': [mean_list_m_1[3]],
        'amb1_s': [mean_list_m_1[4]],
        'shar1_s': [mean_list_m_1[5]],
}

df_m_1 = pd.DataFrame(data = dic_m_1)

categories = ['Attractive', 'Sincere', 'Intelligent', 'Fun', 'Ambitious', 'Share Interests']
categories = [*categories, categories[0]]

mean_attribute = mean_list_m_1
mean_attribute = [*mean_attribute, mean_attribute[0]]



fig = go.Figure(
    data=[
        go.Scatterpolar(r=mean_attribute, theta=categories, fill='toself', name='mean_attribute'),

    ],
    layout=go.Layout(
        title=go.layout.Title(text='Male - What looking for in the opposite sex'),
        polar={'radialaxis': {'visible': True}},
        showlegend=True
    )
)

pyo.plot(fig);

Female - What you think the MOST of your fellow men look for in the opposite sex ?

Male - What you think the MOST of your fellow men look for in the opposite sex ?

Female - What do you think the opposite sex looks for in a date ?

Male - What do you think the opposite sex looks for in a date ?

Female - How do you think you measure up ?

Male - How do you think you measure up ?

Female - How do you think others perceive you ?

Male - How do you think others perceive you ?

In [ ]:
mean_list_m_1 = []
for item in columns_1:
    mean = data_m[item].mean()
    mean_list_m_1.append(mean)

dic_m_1 = {'attr1_s': [mean_list_m_1[0]], 
        'sinc1_s': [mean_list_m_1[1]],
        'intel1_s': [mean_list_m_1[2]],
        'fun1_s': [mean_list_m_1[3]],
        'amb1_s': [mean_list_m_1[4]],
        'shar1_s': [mean_list_m_1[5]],
}

df_m_1 = pd.DataFrame(data = dic_m_1)

categories = ['Attractive', 'Sincere', 'Intelligent', 'Fun', 'Ambitious', 'Share Interests']
categories = [*categories, categories[0]]

mean_attribute = mean_list_m_1
mean_attribute = [*mean_attribute, mean_attribute[0]]



fig = go.Figure(
    data=[
        go.Scatterpolar(r=mean_attribute, theta=categories, fill='toself', name='mean_attribute'),

    ],
    layout=go.Layout(
        title=go.layout.Title(text='Male - What looking for in the opposite sex'),
        polar={'radialaxis': {'visible': True}},
        showlegend=True
    )
)

pyo.plot(fig);