# Reste à faire
1. Renommer les data pour plus de clarté
2. Créer des boucles ou création de définitions afin d'éviter les redondances
3. A voir

Part 1 : Male and Female analysis

In [2]:
# Loading usefull librairies
import pandas as pd

import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

import plotly.graph_objects as go
from plotly.offline import *
import plotly.io as pio
pio.renderers.default = 'browser'



# Display all columns in the .head()
pd.options.display.max_columns = 1000 
# Display all rows in the .head()
pd.options.display.max_rows = 1000

In [3]:
# Loading the dataset
dataset = pd.read_csv('src/Speed_Dating_Data.csv',encoding='ISO-8859-1')

In [4]:
# Visualize the 5 first roww of the dataset
dataset.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [5]:
# Checking the shape
dataset.shape

(8378, 195)

SCALING WAVE TO 10 PTS FOR ALL THE DATASET

In [6]:
# Listing the wave were 100 pts has been evaluated
list_waves = [1,2,3,4,5,10,11,12,13,14,15,16,17,18,19,20,21]

In [7]:
# Getting the list of columns names
dataset.columns.to_list()

['iid',
 'id',
 'gender',
 'idg',
 'condtn',
 'wave',
 'round',
 'position',
 'positin1',
 'order',
 'partner',
 'pid',
 'match',
 'int_corr',
 'samerace',
 'age_o',
 'race_o',
 'pf_o_att',
 'pf_o_sin',
 'pf_o_int',
 'pf_o_fun',
 'pf_o_amb',
 'pf_o_sha',
 'dec_o',
 'attr_o',
 'sinc_o',
 'intel_o',
 'fun_o',
 'amb_o',
 'shar_o',
 'like_o',
 'prob_o',
 'met_o',
 'age',
 'field',
 'field_cd',
 'undergra',
 'mn_sat',
 'tuition',
 'race',
 'imprace',
 'imprelig',
 'from',
 'zipcode',
 'income',
 'goal',
 'date',
 'go_out',
 'career',
 'career_c',
 'sports',
 'tvsports',
 'exercise',
 'dining',
 'museums',
 'art',
 'hiking',
 'gaming',
 'clubbing',
 'reading',
 'tv',
 'theater',
 'movies',
 'concerts',
 'music',
 'shopping',
 'yoga',
 'exphappy',
 'expnum',
 'attr1_1',
 'sinc1_1',
 'intel1_1',
 'fun1_1',
 'amb1_1',
 'shar1_1',
 'attr4_1',
 'sinc4_1',
 'intel4_1',
 'fun4_1',
 'amb4_1',
 'shar4_1',
 'attr2_1',
 'sinc2_1',
 'intel2_1',
 'fun2_1',
 'amb2_1',
 'shar2_1',
 'attr3_1',
 'sinc3_1',
 'fun3_1',
 'intel3_1',
 'amb3_1',
 'attr5_1',
 'sinc5_1',
 'intel5_1',
 'fun5_1',
 'amb5_1',
 'dec',
 'attr',
 'sinc',
 'intel',
 'fun',
 'amb',
 'shar',
 'like',
 'prob',
 'met',
 'match_es',
 'attr1_s',
 'sinc1_s',
 'intel1_s',
 'fun1_s',
 'amb1_s',
 'shar1_s',
 'attr3_s',
 'sinc3_s',
 'intel3_s',
 'fun3_s',
 'amb3_s',
 'satis_2',
 'length',
 'numdat_2',
 'attr7_2',
 'sinc7_2',
 'intel7_2',
 'fun7_2',
 'amb7_2',
 'shar7_2',
 'attr1_2',
 'sinc1_2',
 'intel1_2',
 'fun1_2',
 'amb1_2',
 'shar1_2',
 'attr4_2',
 'sinc4_2',
 'intel4_2',
 'fun4_2',
 'amb4_2',
 'shar4_2',
 'attr2_2',
 'sinc2_2',
 'intel2_2',
 'fun2_2',
 'amb2_2',
 'shar2_2',
 'attr3_2',
 'sinc3_2',
 'intel3_2',
 'fun3_2',
 'amb3_2',
 'attr5_2',
 'sinc5_2',
 'intel5_2',
 'fun5_2',
 'amb5_2',
 'you_call',
 'them_cal',
 'date_3',
 'numdat_3',
 'num_in_3',
 'attr1_3',
 'sinc1_3',
 'intel1_3',
 'fun1_3',
 'amb1_3',
 'shar1_3',
 'attr7_3',
 'sinc7_3',
 'intel7_3',
 'fun7_3',
 'amb7_3',
 'shar7_3',
 'attr4_3',
 'sinc4_3',
 'intel4_3',
 'fun4_3',
 'amb4_3',
 'shar4_3',
 'attr2_3',
 'sinc2_3',
 'intel2_3',
 'fun2_3',
 'amb2_3',
 'shar2_3',
 'attr3_3',
 'sinc3_3',
 'intel3_3',
 'fun3_3',
 'amb3_3',
 'attr5_3',
 'sinc5_3',
 'intel5_3',
 'fun5_3',
 'amb5_3']

In [8]:
# List of features to change into 10 pts instead of 100 pts in waves from list_waves
list_waves_100 = [
            'attr1_1',
            'sinc1_1',
            'intel1_1',
            'fun1_1',
            'amb1_1',
            'shar1_1',

            'attr4_1',
            'sinc4_1',
            'intel4_1',
            'fun4_1',
            'amb4_1',
            'shar4_1',

            'attr2_1',
            'sinc2_1',
            'intel2_1',
            'fun2_1',
            'amb2_1',
            'shar2_1',

            'attr1_2',
            'sinc1_2',
            'intel1_2',
            'fun1_2',
            'amb1_2',
            'shar1_2']

In [9]:
# List of features to change into 10 pts were 100 pts has been attribute in the full columns

list_full_100 = ['attr7_2',
            'sinc7_2',
            'intel7_2',
            'fun7_2',
            'amb7_2',
            'shar7_2',

            'attr4_2',
            'sinc4_2',
            'intel4_2',
            'fun4_2',
            'amb4_2',
            'shar4_2',

            'attr2_2',
            'sinc2_2',
            'intel2_2',
            'fun2_2',
            'amb2_2',
            'shar2_2',

            'attr1_3',
            'sinc1_3',
            'intel1_3',
            'fun1_3',
            'amb1_3',
            'shar1_3',

            'attr7_3',
            'sinc7_3',
            'intel7_3',
            'fun7_3',
            'amb7_3',
            'shar7_3']

REMPLACEMENT DES NUMERO PAR LE TEXTE ASSOCIE

In [10]:
dataset["gender"] = dataset["gender"].apply(lambda x : "Male" if x==1 else "Female")

In [11]:
# Creating the list of columns needed

list_col_df = ['iid',
        'id',
        'gender',
        'wave',
        'attr1_1',
        'sinc1_1',
        'intel1_1',
        'fun1_1',
        'amb1_1',
        'shar1_1',
        'attr4_1',
        'sinc4_1',
        'intel4_1',
        'fun4_1',
        'amb4_1',
        'shar4_1',
        'attr2_1',
        'sinc2_1',
        'intel2_1',
        'fun2_1',
        'amb2_1',
        'shar2_1',
        'attr3_1',
        'sinc3_1',
        'fun3_1',
        'intel3_1',
        'amb3_1',
        'attr5_1',
        'sinc5_1',
        'intel5_1',
        'fun5_1',
        'amb5_1',
        'attr7_2',
        'sinc7_2',
        'intel7_2',
        'fun7_2',
        'amb7_2',
        'shar7_2',
        'attr1_2',
        'sinc1_2',
        'intel1_2',
        'fun1_2',
        'amb1_2',
        'shar1_2',
        'attr4_2',
        'sinc4_2',
        'intel4_2',
        'fun4_2',
        'amb4_2',
        'shar4_2',
        'attr2_2',
        'sinc2_2',
        'intel2_2',
        'fun2_2',
        'amb2_2',
        'shar2_2',
        'attr3_2',
        'sinc3_2',
        'intel3_2',
        'fun3_2',
        'amb3_2',
        'attr5_2',
        'sinc5_2',
        'intel5_2',
        'fun5_2',
        'amb5_2',
        'attr1_3',
        'sinc1_3',
        'intel1_3',
        'fun1_3',
        'amb1_3',
        'shar1_3',
        'attr7_3',
        'sinc7_3',
        'intel7_3',
        'fun7_3',
        'amb7_3',
        'shar7_3',
        'attr4_3',
        'sinc4_3',
        'intel4_3',
        'fun4_3',
        'amb4_3',
        'shar4_3',
        'attr2_3',
        'sinc2_3',
        'intel2_3',
        'fun2_3',
        'amb2_3',
        'shar2_3',
        'attr3_3',
        'sinc3_3',
        'intel3_3',
        'fun3_3',
        'amb3_3',
        'attr5_3',
        'sinc5_3',
        'intel5_3',
        'fun5_3',
        'amb5_3']

In [16]:
# Creating the usefull dataset with only columns needeed
df = pd.DataFrame(data = dataset, columns = list_col_df)

In [17]:
# Dividing the value to get a rate on 10 pts instead of 100 pts base on the wave number
for col2 in list_full_100:
    df[col2] = df[col2]/ 10

In [18]:
# Dividing the value to get a rate on 10 pts instead of 100 pts base on the columns
for col in list_waves_100:
    for wave in list_waves:
        df.loc[df['wave']==wave,col] = (df.loc[df['wave']==wave,col])/ 10

In [ ]:
df.head()

REPLACE MISSING VALUES

In [19]:
percent_missing = df.isnull().sum() * 100 / len(df)
df_missing_value = pd.DataFrame({'column_name' : df.columns,
                                'percent_missing':percent_missing })

df_missing_value.sort_values('percent_missing', ascending=False, inplace=True)

In [ ]:
print(df_missing_value)

In [ ]:
# # usefull_col_na = ['attr1_1',
                    'sinc1_1',
                    'intel1_1',
                    'fun1_1',
                    'amb1_1',
                    'shar1_1',
                    'attr4_1',
                    'sinc4_1',
                    'intel4_1',
                    'fun4_1',
                    'amb4_1',
                    'shar4_1',
                    'attr2_1',
                    'sinc2_1',
                    'intel2_1',
                    'fun2_1',
                    'amb2_1',
                    'shar2_1',
                    'attr3_1',
                    'sinc3_1',
                    'fun3_1',
                    'intel3_1',
                    'amb3_1',
                    'attr5_1',
                    'sinc5_1',
                    'intel5_1',
                    'fun5_1',
                    'amb5_1',
                    'attr1_s',
                    'sinc1_s',
                    'intel1_s',
                    'fun1_s',
                    'amb1_s',
                    'shar1_s',
                    'attr3_s',
                    'sinc3_s',
                    'intel3_s',
                    'fun3_s',
                    'amb3_s',
                    'attr7_2',
                    'sinc7_2',
                    'intel7_2',
                    'fun7_2',
                    'amb7_2',
                    'shar7_2',
                    'attr1_2',
                    'sinc1_2',
                    'intel1_2',
                    'fun1_2',
                    'amb1_2',
                    'shar1_2',
                    'attr4_2',
                    'sinc4_2',
                    'intel4_2',
                    'fun4_2',
                    'amb4_2',
                    'shar4_2',
                    'attr2_2',
                    'sinc2_2',
                    'intel2_2',
                    'fun2_2',
                    'amb2_2',
                    'shar2_2',
                    'attr3_2',
                    'sinc3_2',
                    'intel3_2',
                    'fun3_2',
                    'amb3_2',
                    'attr5_2',
                    'sinc5_2',
                    'intel5_2',
                    'fun5_2',
                    'amb5_2',
                    'attr1_3',
                    'sinc1_3',
                    'intel1_3',
                    'fun1_3',
                    'amb1_3',
                    'shar1_3',
                    'attr7_3',
                    'sinc7_3',
                    'intel7_3',
                    'fun7_3',
                    'amb7_3',
                    'shar7_3',
                    'attr4_3',
                    'sinc4_3',
                    'intel4_3',
                    'fun4_3',
                    'amb4_3',
                    'shar4_3',
                    'attr2_3',
                    'sinc2_3',
                    'intel2_3',
                    'fun2_3',
                    'amb2_3',
                    'shar2_3',
                    'attr3_3',
                    'sinc3_3',
                    'intel3_3',
                    'fun3_3',
                    'amb3_3',
                    'attr5_3',
                    'sinc5_3',
                    'intel5_3',
                    'fun5_3',
                    'amb5_3']

In [ ]:
# for feature in usefull_col_na:
    mean_feature=dataset[feature].mean()
    dataset[feature].fillna(value=mean_feature, inplace=True)

In [ ]:
df.shape

In [ ]:
# Groupby idd to get one row for 1 people with minimum of NaN values
data = dataset.loc[dataset.isnull().sum(axis=1).groupby(dataset.iid).idxmin(),:]

SPLITTING DATA INTO FEMALE and MALE

In [20]:
df_male = df.loc[df.gender == 'Male',:]

In [21]:
df_male.shape

(4194, 100)

In [22]:
df_female = df.loc[df.gender == 'Female',:]

## VISUALISATIONS

In [832]:
question1_time1 = ['attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1', 'shar1_1']
question1_time2 = ['attr1_2','sinc1_2','intel1_2','fun1_2','amb1_2', 'shar1_2']
question1_time3 = ['attr1_3','sinc1_3','intel1_3','fun1_3','amb1_3','shar1_3']
question2_time1 = ['attr4_1','sinc4_1','intel4_1','fun4_1','amb4_1','shar4_1']
question2_time2 = ['attr4_2','sinc4_2','intel4_2','fun4_2','amb4_2','shar4_2']
question2_time3 = ['attr4_3','sinc4_3','intel4_3','fun4_3','amb4_3','shar4_3']
question3_time1 = ['attr2_1','sinc2_1','intel2_1','fun2_1','amb2_1','shar2_1']
question3_time2 = [ 'attr2_2','sinc2_2','intel2_2','fun2_2','amb2_2','shar2_2']
question3_time3 = ['attr2_3','sinc2_3','intel2_3','fun2_3','amb2_3','shar2_3']
question4_time1 = ['attr3_1','sinc3_1','intel3_1','fun3_1','amb3_1']
question4_time2 = ['attr3_2','sinc3_2','intel3_2','fun3_2','amb3_2']
question4_time3 = ['attr3_3','sinc3_3','intel3_3','fun3_3','amb3_3']
question5_time1 = ['attr5_1','sinc5_1','intel5_1','fun5_1','amb5_1']
question5_time2 = ['attr5_2','sinc5_2','intel5_2','fun5_2','amb5_2']
question5_time3 = ['attr5_3','sinc5_3','intel5_3','fun5_3','amb5_3']

In [840]:
list_questions = [question1_time1, 
                    question1_time2,
                    question1_time3,
                    question2_time1,
                    question2_time2,
                    question2_time3,
                    question3_time1,
                    question3_time2,
                    question3_time3,
                    question4_time1,
                    question4_time2,
                    question4_time3,
                    question5_time1,
                    question5_time2,
                    question5_time3

]

In [830]:

    print(key)

question1_time1
question1_time2
question1_time3
question2_time1
question2_time2
question2_time3
question3_time1
question3_time2
question3_time3
question4_time1
question4_time2
question4_time3
question5_time1
question5_time2
question5_time3

In [ ]:
attribute_rating_time2 = [ 'attr7_2',
                            'sinc7_2',
                            'intel7_2',
                            'fun7_2',
                            'amb7_2',
                            'shar7_2']
attribute_rating_time3 = ['attr7_3',
                            'sinc7_3',
                            'intel7_3',
                            'fun7_3',
                            'amb7_3',
                            'shar7_3']

 ## ANALYSIS

Question 1 : What you looking for in the opposite sex ?

Female

In [ ]:
gender_list = ['female', 'male']
question_number = [1, 2 ,3, 4, 5]
time =['time1', 'time2', 'time3']

In [ ]:
question_list = ['What are you looking for in the opposite sex?',
                'what you think the MOST of your fellow men/women look for in the opposite sex ?',
                'What do you think the opposite sex looks for in a date ?',
                'How do you think you measure up?',
                'How do you think others perceive you ?']

In [ ]:
indice_list_mean = [0, 1, 2, 3 , 4, 5]

In [ ]:
mean_question_list =[]
for gender in gender_list:
    for number in question_number:
        for moment in time:
            mean_question_list.append(f"mean_question{number}_{gender}_{moment}")

In [786]:
mean_question_list

['mean_question1_female_time1',
 'mean_question1_female_time2',
 'mean_question1_female_time3',
 'mean_question2_female_time1',
 'mean_question2_female_time2',
 'mean_question2_female_time3',
 'mean_question3_female_time1',
 'mean_question3_female_time2',
 'mean_question3_female_time3',
 'mean_question4_female_time1',
 'mean_question4_female_time2',
 'mean_question4_female_time3',
 'mean_question5_female_time1',
 'mean_question5_female_time2',
 'mean_question5_female_time3']

In [ ]:
question_list_number =[]

for number in question_number:
    for moment in time:
        question_list_number.append(f"question{number}_{moment}")

In [787]:
question_list_number

['question1_time1',
 'question1_time2',
 'question1_time3',
 'question2_time1',
 'question2_time2',
 'question2_time3',
 'question3_time1',
 'question3_time2',
 'question3_time3',
 'question4_time1',
 'question4_time2',
 'question4_time3',
 'question5_time1',
 'question5_time2',
 'question5_time3']

In [747]:
dict_question_list =[]
for gender in gender_list:
    for number in question_number:
        for moment in time:
            dict_question_list.append(f"dic_question{number}_{gender}_{moment}")

In [788]:
dic_question_list

['dic_question1_female_time1',
 'dic_question1_female_time2',
 'dic_question1_female_time3',
 'dic_question2_female_time1',
 'dic_question2_female_time2',
 'dic_question2_female_time3',
 'dic_question3_female_time1',
 'dic_question3_female_time2',
 'dic_question3_female_time3',
 'dic_question4_female_time1',
 'dic_question4_female_time2',
 'dic_question4_female_time3',
 'dic_question5_female_time1',
 'dic_question5_female_time2',
 'dic_question5_female_time3',
 'dic_question1_male_time1',
 'dic_question1_male_time2',
 'dic_question1_male_time3',
 'dic_question2_male_time1',
 'dic_question2_male_time2',
 'dic_question2_male_time3',
 'dic_question3_male_time1',
 'dic_question3_male_time2',
 'dic_question3_male_time3',
 'dic_question4_male_time1',
 'dic_question4_male_time2',
 'dic_question4_male_time3',
 'dic_question5_male_time1',
 'dic_question5_male_time2',
 'dic_question5_male_time3']

In [ ]:
df_question_list =[]
for gender in gender_list:
    for number in question_number:
        for moment in time:
            df_question_list.append(f"dic_question{number}_{gender}_{moment}")

In [790]:
df_question_list

['dic_question1_female_time1',
 'dic_question1_female_time2',
 'dic_question1_female_time3',
 'dic_question2_female_time1',
 'dic_question2_female_time2',
 'dic_question2_female_time3',
 'dic_question3_female_time1',
 'dic_question3_female_time2',
 'dic_question3_female_time3',
 'dic_question4_female_time1',
 'dic_question4_female_time2',
 'dic_question4_female_time3',
 'dic_question5_female_time1',
 'dic_question5_female_time2',
 'dic_question5_female_time3',
 'dic_question1_male_time1',
 'dic_question1_male_time2',
 'dic_question1_male_time3',
 'dic_question2_male_time1',
 'dic_question2_male_time2',
 'dic_question2_male_time3',
 'dic_question3_male_time1',
 'dic_question3_male_time2',
 'dic_question3_male_time3',
 'dic_question4_male_time1',
 'dic_question4_male_time2',
 'dic_question4_male_time3',
 'dic_question5_male_time1',
 'dic_question5_male_time2',
 'dic_question5_male_time3']

In [ ]:
CHECK

In [789]:
question_list

['What are you looking for in the opposite sex?',
 'what you think the MOST of your fellow men/women look for in the opposite sex ?',
 'What do you think the opposite sex looks for in a date ?',
 'How do you think you measure up?',
 'How do you think others perceive you ?']

In [810]:
for feature in dict_questions[key]:
    print(feature)

attr1_1
sinc1_1
intel1_1
fun1_1
amb1_1
shar1_1

In [ ]:
# a travailler

# Splitting the process mean question by gender and using the right df by gender
for gender in gender_list:
    if gender == "male":
        df = df_male
    else :
        df = df_female

    # Creating a list of name variable getting the mean of each features in question list
    mean_question_list =[]
    for number in question_number:  
        for moment in time:                    # time = ['time1', 'time2', 'time3']
            mean_question_list.append(f"mean_question{number}_{gender}_{moment}")  #  ['mean_question1_female_time1']
            # Creating a list of name variable getting the feature by questions
            question_list_number = []
            for number in question_number:        # question number = [1, 2, 3, 4, 5]
                for moment in time:                  # time = ['time1', 'time2', 'time3']
                    question_list_number.append(f"question{number}_{moment}")   # ['question1_time1']
   
    # Getting a list of the feature by question
    list_item = []
for feature in dict_questions[key]: 
    print('-----')
    print(item)
    print('item ok ')
    print("-----")      # item attr1_1 sinc1_1 intel1_1
    print('-----')
    print(dict_questions[key])
    print('dict_questions[key] ok ')
    print("-----")  
    list_item.append(item)
    print('-----')
    print(list_item)
    print('list_item ok ')
    print("-----")
# Getting the mean value of feature of question   
    mean_list_feature =[]
for feature in list_item:
    print('-----')
    print(feature)
    print('feature ok ')
    print("-----")
    print('-----')
    print(list_item)
    print('list_item ok ')
    print("-----")
    mean = df.loc[:,feature].mean()
    mean_list_feature.append(mean)
    print('-----')
    print(mean_list_feature)
    print('mean_list_feature ok ')
    print("-----")
    
# Put value un a dict  
my_dict = {"feature" :[], 'mean_value': []};

for dict in dict_question_list:
    my_dict["feature"].append(feature)
    my_dict["mean_value"].append(mean)
print('-----')
print(dict)
print('dict ok ')
print("-----")
print('-----')
print(dict_question_list)
print('dict_question_list ok ')
print("-----")

for data in df_question_list:
    data = pd.DataFrame(data = my_dict)

    categories = ['Attractive', 'Sincere', 'Intelligent', 'Fun', 'Ambitious', 'Share Interests']
    categories = [*categories, categories[0]]

    mean_attribute = mean_question
    mean_attribute = [*mean_attribute, mean_attribute[0]]



    fig = go.Figure(
        data=[
            go.Scatterpolar(r=mean_attribute, theta=categories, fill='toself', name='mean_attribute'),

        ],
        layout=go.Layout(
            title=go.layout.Title(text=f'{gender} - {question_list}'),
            polar=dict(
            radialaxis=dict(
            visible=True,
            range = [0,10])),
            showlegend=True
    ))

In [834]:
dic_mean_feature_question

{'feature': ['attr1_1',
  'sinc1_1',
  'intel1_1',
  'fun1_1',
  'amb1_1',
  'shar1_1',
  'attr1_2',
  'sinc1_2',
  'intel1_2',
  'fun1_2',
  'amb1_2',
  'shar1_2',
  'attr1_3',
  'sinc1_3',
  'intel1_3',
  'fun1_3',
  'amb1_3',
  'shar1_3',
  'attr4_1',
  'sinc4_1',
  'intel4_1',
  'fun4_1',
  'amb4_1',
  'shar4_1',
  'attr4_2',
  'sinc4_2',
  'intel4_2',
  'fun4_2',
  'amb4_2',
  'shar4_2',
  'attr4_3',
  'sinc4_3',
  'intel4_3',
  'fun4_3',
  'amb4_3',
  'shar4_3',
  'attr2_1',
  'sinc2_1',
  'intel2_1',
  'fun2_1',
  'amb2_1',
  'shar2_1',
  'attr2_2',
  'sinc2_2',
  'intel2_2',
  'fun2_2',
  'amb2_2',
  'shar2_2',
  'attr2_3',
  'sinc2_3',
  'intel2_3',
  'fun2_3',
  'amb2_3',
  'shar2_3',
  'attr3_1',
  'sinc3_1',
  'intel3_1',
  'fun3_1',
  'amb3_1',
  'attr3_2',
  'sinc3_2',
  'intel3_2',
  'fun3_2',
  'amb3_2',
  'attr3_3',
  'sinc3_3',
  'intel3_3',
  'fun3_3',
  'amb3_3',
  'attr5_1',
  'sinc5_1',
  'intel5_1',
  'fun5_1',
  'amb5_1',
  'attr5_2',
  'sinc5_2',
  'intel5_2',
  'fun5_2',
  'amb5_2',
  'attr5_3',
  'sinc5_3',
  'intel5_3',
  'fun5_3',
  'amb5_3'],
 'mean_feature': [5.636974463453688,
  4.566683313156341,
  5.136455316046516,
  4.7778848841903905,
  3.0620722584172992,
  3.4345994380000953,
  6.1432327833716815,
  4.445103078436048,
  4.813565992228326,
  4.705579234451936,
  2.976847202395839,
  3.4796741276216583,
  2.6411024929187734,
  1.6331600457122923,
  1.921532635415399,
  1.6298253975752135,
  1.008621659923074,
  1.1926544070755942,
  4.270407126083408,
  2.192317462542831,
  2.275088917484908,
  2.9163931963728675,
  1.7301393137956875,
  2.1931334813401446,
  2.8381786300342258,
  1.1284103958616594,
  1.1408554862706486,
  1.5590538078047103,
  0.8557702033225498,
  1.0987570600278183,
  26.187598747259475,
  10.320363865731787,
  11.576604692530774,
  14.384796795678117,
  8.839081160944462,
  10.957481488892116,
  5.248492557278224,
  4.327345625130773,
  4.435932773423617,
  4.820774454579583,
  4.17499404194938,
  3.563849982557023,
  2.659573583384125,
  1.526235558472815,
  1.5088467795020866,
  1.7456078440933314,
  1.351735169956397,
  1.218508968384203,
  23.969234166582282,
  11.293949926980405,
  12.44408114264381,
  14.578449398091607,
  10.295943477831202,
  11.532899260787348,
  6.9467660664656155,
  8.107887386265006,
  8.473689148423757,
  7.509434588005608,
  7.526119720494794,
  6.991908094372672,
  7.739876773550962,
  8.321903822999722,
  7.444278416118797,
  7.439003778447803,
  7.124367958517367,
  7.970892025603245,
  8.39784956004644,
  7.49965752118009,
  7.330856342398877,
  6.8633398137696275,
  7.813766683689463,
  8.298024521656972,
  7.347628557678583,
  7.515805445626882,
  6.803621490413048,
  7.24403738280757,
  7.881095717769866,
  7.23826879759557,
  7.35804323387184,
  6.755936264397455,
  7.518781158672856,
  7.9538851641739745,
  7.1010884046759495,
  7.04926293622142]}

In [843]:
## SECOND TRIAL
mean_feature_list = []
dic_mean_feature_question = {'feature' : [],'mean_feature' : []}

# Splitting the process mean question by gender and using the right df by gender
for gender in gender_list:
    if gender == "male":
        df = df_male
    else :
        df = df_female
    for question in list_questions:
        for feature in question:
            mean_feature = df[feature].mean()
            mean_feature_list.append(mean_feature)
            dic_mean_feature_question["feature"].append(feature)
            dic_mean_feature_question["mean_feature"].append(mean_feature)
    data_mean_feature = pd.DataFrame(data =dic_mean_feature_question )

In [844]:
data_mean_feature

      feature  mean_feature
0     attr1_1      4.307359
1     sinc1_1      4.879817
2    intel1_1      5.191700
3      fun1_1      4.666916
4      amb1_1      3.997666
5     shar1_1      3.712057
6     attr1_2      5.169967
7     sinc1_2      4.511779
8    intel1_2      4.948585
9      fun1_2      4.607745
10     amb1_2      3.737934
11    shar1_2      3.823966
12    attr1_3      2.234967
13    sinc1_3      1.697500
14   intel1_3      1.964333
15     fun1_3      1.602981
16     amb1_3      1.164198
17    shar1_3      1.346135
18    attr4_1      3.928966
19    sinc4_1      2.408944
20   intel4_1      2.561677
21     fun4_1      2.900600
22     amb4_1      2.364988
23    shar4_1      2.318671
24    attr4_2      2.507221
25    sinc4_2      1.244651
26   intel4_2      1.273608
27     fun4_2      1.469488
28     amb4_2      1.020509
29    shar4_2      1.157723
30    attr4_3     24.888822
31    sinc4_3     11.296397
32   intel4_3     11.529829
33     fun4_3     14.038319
34     amb4_3      9.674673
35    shar4_3     11.440287
36    attr2_1      7.245537
37    sinc2_1      3.693515
38   intel2_1      3.721838
39     fun2_1      5.137159
40     amb2_1      3.154789
41    shar2_1      3.814952
42    attr2_2      3.170876
43    sinc2_2      1.271333
44   intel2_2      1.299565
45     fun2_2      1.849328
46     amb2_2      1.044009
47    shar2_2      1.346580
48    attr2_3     25.945683
49    sinc2_3     10.635445
50   intel2_3     11.441793
51     fun2_3     15.274197
52     amb2_3      8.713139
53    shar2_3     12.398614
54    attr3_1      7.239082
55    sinc3_1      8.466312
56   intel3_1      8.297167
57     fun3_1      7.894988
58     amb3_1      7.629454
59    attr3_2      7.242738
60    sinc3_2      8.133340
61   intel3_2      8.122631
62     fun3_2      7.757949
63     amb3_2      7.490967
64    attr3_3      7.312992
65    sinc3_3      8.215145
66   intel3_3      8.364100
67     fun3_3      7.785854
68     amb3_3      7.427437
69    attr5_1      7.007617
70    sinc5_1      8.048688
71   intel5_1      8.240282
72     fun5_1      7.458830
73     amb5_1      7.702539
74    attr5_2      6.847661
75    sinc5_2      7.581703
76   intel5_2      7.794675
77     fun5_2      7.301311
78     amb5_2      7.298695
79    attr5_3      6.856985
80    sinc5_3      7.721281
81   intel5_3      7.910367
82     fun5_3      7.179587
83     amb5_3      7.002813
84    attr1_1      5.636974
85    sinc1_1      4.566683
86   intel1_1      5.136455
87     fun1_1      4.777885
88     amb1_1      3.062072
89    shar1_1      3.434599
90    attr1_2      6.143233
91    sinc1_2      4.445103
92   intel1_2      4.813566
93     fun1_2      4.705579
94     amb1_2      2.976847
95    shar1_2      3.479674
96    attr1_3      2.641102
97    sinc1_3      1.633160
98   intel1_3      1.921533
99     fun1_3      1.629825
100    amb1_3      1.008622
101   shar1_3      1.192654
102   attr4_1      4.270407
103   sinc4_1      2.192317
104  intel4_1      2.275089
105    fun4_1      2.916393
106    amb4_1      1.730139
107   shar4_1      2.193133
108   attr4_2      2.838179
109   sinc4_2      1.128410
110  intel4_2      1.140855
111    fun4_2      1.559054
112    amb4_2      0.855770
113   shar4_2      1.098757
114   attr4_3     26.187599
115   sinc4_3     10.320364
116  intel4_3     11.576605
117    fun4_3     14.384797
118    amb4_3      8.839081
119   shar4_3     10.957481
120   attr2_1      5.248493
121   sinc2_1      4.327346
122  intel2_1      4.435933
123    fun2_1      4.820774
124    amb2_1      4.174994
125   shar2_1      3.563850
126   attr2_2      2.659574
127   sinc2_2      1.526236
128  intel2_2      1.508847
129    fun2_2      1.745608
130    amb2_2      1.351735
131   shar2_2      1.218509
132   attr2_3     23.969234
133   sinc2_3     11.293950
134  intel2_3     12.444081
135    fun2_3     14.578449
136    amb2_3     10.295943
137   shar2_3     11.532899
138   attr3_1      6.946766
139   sinc3_1      8.107887
140  intel3_1      8.473689
141    fun3_1      7.509435
142    amb3_1      7.526120
143   attr3_2      6.991908
144   sinc3_2      7.739877
145  intel3_2      8.321904
146    fun3_2      7.444278
147    amb3_2      7.439004
148   attr3_3      7.124368
149   sinc3_3      7.970892
150  intel3_3      8.397850
151    fun3_3      7.499658
152    amb3_3      7.330856
153   attr5_1      6.863340
154   sinc5_1      7.813767
155  intel5_1      8.298025
156    fun5_1      7.347629
157    amb5_1      7.515805
158   attr5_2      6.803621
159   sinc5_2      7.244037
160  intel5_2      7.881096
161    fun5_2      7.238269
162    amb5_2      7.358043
163   attr5_3      6.755936
164   sinc5_3      7.518781
165  intel5_3      7.953885
166    fun5_3      7.101088
167    amb5_3      7.049263

In [808]:
## A garder fonctione bien
mean_question1_female_time1 = []
for feature in question1_time1:
    mean = df_female[feature].mean()
    mean_question1_female_time1.append(mean)

dic_question1_female = {question1_time1[0]: [mean_question1_female_time1[0]], 
                        question1_time1[1]: [mean_question1_female_time1[1]],
                        question1_time1[2]: [mean_question1_female_time1[2]],
                        question1_time1[3]: [mean_question1_female_time1[3]],
                        question1_time1[4]: [mean_question1_female_time1[4]],
                        question1_time1[5]: [mean_question1_female_time1[5]]
                }

df_question1_female = pd.DataFrame(data = dic_question1_female)

categories = ['Attractive', 'Sincere', 'Intelligent', 'Fun', 'Ambitious', 'Share Interests']
categories = [*categories, categories[0]]

mean_attribute = mean_question1_female_time1
mean_attribute = [*mean_attribute, mean_attribute[0]]

fig = go.Figure(
    data=[
        go.Scatterpolar(r=mean_attribute, theta=categories, fill='toself', name='mean_attribute'),

    ],
    layout=go.Layout(
        title=go.layout.Title(text='Female - What you looking for in the opposite sex ?'),
        polar=dict(
                radialaxis=dict(
                visible=True,
                range = [0,10])),
                showlegend=True
    ))

pyo.plot(fig);

TypeError: 'str' object is not callable

In [839]:
nom_de_variable1 = ['feature1', 'feature2','feature3']
nom_de_variable2 = ['feature4', 'feature5','feature6']
nom_de_variable3 = ['feature7', 'feature8','feature9']
nom_de_variable4 = ['feature10', 'feature11','feature12']

list_variables = [nom_de_variable1, nom_de_variable2, nom_de_variable3, nom_de_variable4]

for variable in list_variables:
    for feature in variable:
        print(feature)

feature1
feature2
feature3
feature4
feature5
feature6
feature7
feature8
feature9
feature10
feature11
feature12